services:
  whatsapp_go:
    container_name: go-whatsapp
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    build:
      context: .
      dockerfile: ./docker/golang.Dockerfile
    restart: "on-failure"
    ports:
      - "3001:3001"
    env_file:
      - src/.env
    networks:
      - router-network
    volumes:
      - ./storages:/app/storages

networks:
  router-network:
    external: true
    name: router-manager_router-network